# .pre-commit-config.yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.275"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args:
          - src
          - -vv
          - -i
          - --fail-under=90
          # files to exclude
          - --exclude=src/finetuning/utils/model_utils.py
          - --exclude=src/pretraining/models_mae.py
          - --exclude=src/pretraining/main_pretrain.py
          - --exclude=src/pretraining/engine_pretrain.py
          - --exclude=src/pretraining/util/video_vit.py
          - --exclude=src/pretraining/util/misc.py
          - --exclude=src/pretraining/util/lr_sched.py
          - --exclude=src/pretraining/util/logging.py
          - --exclude=src/pretraining/util/env.py
        pass_filenames: false
