task: pretraining

# dataset path
dataset_source_path: "" # path to dataset
csv_file_name: "" # csv file name

# mae args
batch_size: 8
epochs: 100
accum_iter: 1
model: "mae_vit_large_patch16"
input_size: 96
mask_ratio: 0.8
weight_decay: 0.05
lr: null
blr: 1e-3
min_lr: 0.0
warmup_epochs: 40
path_to_data_dir: ""
output_dir: "./mae_output_dir"
log_dir: "./mae_output_dir"
device: "cuda"
pretrained_weights: ""
num_workers: 0
decoder_embed_dim: 512
decoder_depth: 4
decoder_num_heads: 16
t_patch_size: 2
num_frames: 16
pred_t_dim: 8
cls_embed: True
sep_pos_embed: True
cls_embed_decoder: False
sep_pos_embed_decoder: False
